/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 ./public/gramps.glb --keepnames --meta --types 
*/

import * as THREE from 'three'
import React, { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh
  }
  materials: {}
}

const Gramps = forwardRef((props: JSX.IntrinsicElements['group'], ref) => {
  const { nodes, materials } = useGLTF('/gramps.glb') as GLTFResult
  return (
    <group ref={ref as any} {...props} dispose={null}>
      <mesh name='mesh_0' geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
    </group>
  )
})

export default Gramps

useGLTF.preload('/gramps.glb')
